### ISSUE TITLE
Create Remindi home screen

### ISSUE THREAD

**Issue by 2tanayk** [dsctsec/ASJ_2021#2]
<img src="https://user-images.githubusercontent.com/60653277/147362601-22a7fa5c-fbd4-48c1-8e26-5df0e3e1d920.jpeg" width="200" height="400" />
<br>
<img src="https://user-images.githubusercontent.com/60653277/147362866-8880f1ec-9dbb-4c43-9b25-3a5f0b2e177c.png" width="200" height="400" />

**Comment by hridayK** [comment]
Assign me this one
