### ISSUE TITLE
Create Remindi weekday screen 

### ISSUE THREAD

**Issue by 2tanayk** [dsctsec/ASJ_2021#4]
<img src="https://user-images.githubusercontent.com/60653277/147363219-8377819c-5deb-4ec1-a4a6-e58838d00002.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/60653277/147363278-454d3e3b-8448-4af0-9ef6-64101ba5fb78.png" width="200" height="400" />

**Comment by VirenKeswani** [comment]
ok i will do this ( Viren Keswani)
