### ISSUE TITLE
Create Remindi lecture edit screen

### ISSUE THREAD

**Issue by 2tanayk** [dsctsec/ASJ_2021#5]
<img src="https://user-images.githubusercontent.com/60653277/147369224-b5ab8c30-adce-404b-b5aa-7f91fdae2bb2.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/60653277/147369283-32ba278a-6cc0-4787-bc21-f1d15d5474a6.png" width="200" height="400" />

**Comment by Krishanadave671** [comment]
I  will do this

**Comment by Krishanadave671** [comment]
I will do this
